#!/bin/bash
#
# A script to aid with Riak development.
#
#>Usage:
#>    riak-dev [OPTIONS] command [ARGS]
#>
#>Examples:
#>    riak-dev --devrel put num-keys=100

usage() {
    echo
    grep '^#>' $0 | tr -d '#>'
}

error() {
    msg=$1

    echo $msg
    usage
    exit 1
}

log() {
    msg=$1
    echo $msg
}

setup_gitcache() {
    if [ -e ~/gitcache ]; then
        error "gitcache exists already"
    fi

    gc_dir=~/gitcache
    cd ~/
    git clone git@github.com:basho/gitcache.git
    cd $gc_dir
    mkdir riak
    cd riak
    git init --bare
    sh ../add_riak_repos.sh
    git fetch --all

    echo "" >> ~/.bashrc
    echo ". $gc_dir/setup.sh" >> ~/.bashrc

    log "gitcache setup successfully"
}

while test $# -gt 0
do
    case $1 in
        --devrel)
            devrel=yes
            ;;
        -*)
            error "Unrecognized option: $1"
            ;;
        *)
            break
            ;;
    esac
    shift
done

CMD=$1
shift

case $CMD in
    put)
        $BASHO_BENCH $TOOLS_HOME/bench_cfgs/put.config
        ;;
    setup-gitcache)
        setup_gitcache
        ;;
    *)
        usage
        error "command $CMD not understood"
        ;;
esac
